---
title: "Dashboard: instacart dataset"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: yeti
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
data("instacart")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Scatter plot: department number over the week

```{r}
instacart_df = 
  instacart %>% 
  janitor::clean_names() %>% 
  mutate(day_number = order_dow +1) %>% 
  mutate(day_of_week  = lubridate::wday(day_number, label = FALSE)) %>% 
  select(order_id, product_id, day_of_week, department, aisle, order_number)

instacart_df %>%  
  count(day_of_week, department) %>% 
plot_ly(
    x = ~day_of_week, y = ~n, type = "scatter", color = ~department, alpha = 0.5, colors = "viridis")
  
```

Column {data-width=350}
-----------------------------------------------------------------------

### bar plot: aisle number

```{r}
instacart%>%
  count(aisle, name = "n") %>%
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n, .desc = TRUE)) %>% 
plot_ly(
    x = ~aisle, y = ~n, type = "bar")
```

### box plot: On Tuesday, when people buy items in produce department

```{r}
instacart %>% 
  filter(department == "produce",order_dow == "2") %>%
  plot_ly(
    x = ~aisle, y = ~order_hour_of_day, type = "box", color = ~aisle, alpha = .5
  )
```


